# Generated by Django 5.1.1 on 2024-09-20 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('job_title', models.CharField(max_length=100, verbose_name='job_title')),
                ('experience', models.IntegerField(verbose_name='experience')),
                ('desc', models.CharField(max_length=500, verbose_name='desc')),
                ('link', models.URLField(verbose_name='link')),
                ('skill_1', models.CharField(max_length=50, verbose_name='skill_1')),
                ('skill_2', models.CharField(max_length=50, verbose_name='skill_2')),
                ('skill_3', models.CharField(max_length=50, verbose_name='skill_3')),
                ('payment', models.IntegerField(verbose_name='payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobpost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
