# Generated by Django 5.1.1 on 2024-09-20 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_title', models.CharField(max_length=100, verbose_name='experience_title')),
                ('experience_company', models.CharField(max_length=100, verbose_name='experience_company')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(verbose_name='end_date')),
                ('exp_description', models.TextField(blank=True, null=True, verbose_name='exp_description')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='account.dashboard')),
            ],
        ),
    ]
