# Generated by Django 5.1.1 on 2024-09-20 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(verbose_name='dob')),
                ('street_add', models.CharField(max_length=255, verbose_name='street_add')),
                ('pin', models.IntegerField(verbose_name='pin')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('dashboard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='account.dashboard')),
            ],
        ),
    ]
