# Generated by Django 5.1.1 on 2024-09-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_dashboard_work_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='title',
        ),
    ]
