# Generated by Django 5.1.1 on 2024-09-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_chatmessage_message_alter_chatmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
