# Generated by Django 5.1.1 on 2024-09-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_chatmessage_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
