# Generated by Django 5.1.1 on 2024-09-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
